"""
Full-dictionary coverage test: for every domain term, generate plausible mis-transcriptions,
run each through correct_text() inside a neutral carrier sentence, and report the catch-rate
per term, per corruption operator, and the concrete list of terms Mozhi fails to recover.

THIS IS A SYNTHETIC TEST. The corruptions are generated by rules, not recorded from speakers.
It measures robustness to the kinds of error the rules imitate; it is NOT a measurement of
real-world STT accuracy, which needs real recordings (scripts/evaluate_accuracy.py). Real
Whisper errors are dominated by substitutions with real words ("read" for "RAID"), which rules
only partly imitate. The operators are deliberately orthographic / phonetic-rule based and not
Metaphone based, because Mozhi scores with Metaphone and a Metaphone-built corruption set
would flatter it.

Variant families, per term
  canonical      the term exactly as the dictionary spells it. A CONTROL: it must come back
                 unchanged. A failure here is a pipeline defect, not a coverage gap.
  acronym_map    spoken forms already hand-enumerated in ACRONYM_PHONETIC_MAP. Exact lookups,
                 so ~100% by construction: a regression check, not a coverage measure.
  phrase_alias   entries in PHRASE_ALIASES. Same caveat.
  spelled        letter-by-letter spelling of an acronym ("ess ess dee"): the composer path.
  spelled_token  a phrase with its acronym token spelled out ("eye pea address").
  synthetic      rule-based corruptions (see OPERATORS). The informative family.

A variant is RECOVERED when the corrected sentence equals the carrier with the canonical term in
place, compared WORD BY WORD, case- and punctuation-insensitively (the same convention as
scripts/evaluate_accuracy.py). So "two factor authentication" counts as recovering "two-factor
authentication" (only the hyphen differs), while partial matches, duplicated words ("firewall
firewall") and collateral edits to the carrier still count as failures. A byte-exact column is
kept so the cosmetic gap stays visible. Outcomes: recovered | missed (Mozhi changed nothing) |
garbled (the right term is in the output but the sentence is not right: leftover, duplicated or
swallowed words) | wrong (something else came out).

Plurals are not generated: "routers" is correct English, and whether Mozhi should singularize it
is a product decision, not a phonetic mis-transcription.

Deterministic: variant choice is ordered by a CRC32 of (term, operator, text), never by an RNG.

Run:
    PYTHONPATH=. python3 scripts/dictionary_coverage.py [--workers N] [--limit N] [--terms a,b]
Writes reports/dictionary_coverage_variants.csv, _terms.csv and _summary.txt.
"""
import argparse
import csv
import os
import re
import statistics
import sys
import time
import zlib
from collections import Counter, defaultdict
from collections.abc import Callable
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass
from pathlib import Path

from app.acronym_map import ACRONYM_PHONETIC_MAP, PHRASE_ALIASES
from app.dictionary import get_terms
from app.letter_composer import LETTER_SOUNDS
from app.pipeline import DEFAULT_THRESHOLD, correct_text
from app.tokenizer import normalize, tokenize

REPO_ROOT = Path(__file__).parent.parent
REPORTS = REPO_ROOT / "reports"
VARIANTS_CSV = REPORTS / "dictionary_coverage_variants.csv"
TERMS_CSV = REPORTS / "dictionary_coverage_terms.csv"
SUMMARY_TXT = REPORTS / "dictionary_coverage_summary.txt"

# Neutral carrier: none of its words match a domain term (tests assert this).
CARRIER = "please check the {} now"
SYNTHETIC_CAP = 10  # max synthetic variants kept per term, spread round-robin over operators

CANONICAL, ACRONYM_MAP, PHRASE_ALIAS, SPELLED, SPELLED_TOKEN, SYNTHETIC = (
    "canonical", "acronym_map", "phrase_alias", "spelled", "spelled_token", "synthetic")
FAMILIES = (CANONICAL, ACRONYM_MAP, PHRASE_ALIAS, SPELLED, SPELLED_TOKEN, SYNTHETIC)
TAUTOLOGICAL = {CANONICAL, ACRONYM_MAP, PHRASE_ALIAS}  # ~100% by construction; excluded from "evaluated" rates

# Acronyms people say as words, so word-style corruptions ("land" for LAN) are plausible for
# them. Letter-name acronyms (SSD, VPN...) are not corrupted as words: nobody says "sst".
WORDLIKE_ACRONYMS = frozenset({"LAN", "WAN", "RAM", "NIC", "SOC", "NAS", "NAC", "WAF", "RAID", "DIMM",
                               "BIOS", "UEFI", "NVMe", "SCSI", "VLAN", "VXLAN"})
FILLER_WORDS = frozenset({"and", "of", "the", "for", "to", "as", "in"})
VOWELS = "aeiou"
CONSONANT_SWAPS = {"b": "p", "p": "b", "d": "t", "t": "d", "g": "k", "k": "g", "v": "f", "f": "v",
                   "z": "s", "s": "z", "c": "k", "j": "g", "m": "n", "n": "m", "l": "r", "r": "l"}
RESPELL_RULES = [("ph", "f"), ("ck", "k"), ("ee", "ea"), ("ea", "ee"), ("ai", "ay"), ("ay", "ai"),
                 ("ou", "ow"), ("ow", "ou"), ("tion", "shun"), ("sion", "shun"), ("gh", ""),
                 ("wh", "w"), ("kn", "n"), ("wr", "r"), ("y", "i"), ("i", "y"), ("ce", "se"), ("se", "ce")]
DIGIT_WORDS = dict(zip("0123456789", ["oh", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))

# The first spoken variant of each letter ("ess", "dee", "double you"): the canonical spelling.
LETTER_VARIANTS: dict[str, list[str]] = {}
for _sound, (_letter, _unamb) in LETTER_SOUNDS.items():
    LETTER_VARIANTS.setdefault(_letter, []).append(_sound)


# --- variants --------------------------------------------------------------------------------------------

@dataclass(frozen=True)
class Variant:
    term: str
    family: str
    operator: str
    text: str  # what the "STT" said


def _key(term: str, operator: str, text: str) -> int:
    return zlib.crc32(f"{term}|{operator}|{text}".encode())


def split_words(term: str) -> list[str]:
    """Words of a term: split on spaces and hyphens (an STT transcript has neither hyphens nor case)."""
    return [w for w in re.split(r"[\s\-]+", term) if w]


def _eligible_site(word: str) -> bool:
    return (word.isalpha() and len(word) >= 4) or word in WORDLIKE_ACRONYMS


# word-level operators: a lowercase word -> different lowercase spellings (each >= 3 letters)

def op_vowel_swap(w: str) -> list[str]:
    return [w[:i] + v + w[i + 1:] for i, ch in enumerate(w) if ch in VOWELS for v in VOWELS if v != ch]


def op_consonant_swap(w: str) -> list[str]:
    return [w[:i] + CONSONANT_SWAPS[ch] + w[i + 1:] for i, ch in enumerate(w) if ch in CONSONANT_SWAPS]


def op_double_consonant(w: str) -> list[str]:
    out = [w[:i + 1] + ch + w[i + 1:] for i, ch in enumerate(w[:-1])
           if i > 0 and ch.isalpha() and ch not in VOWELS and w[i + 1] != ch and w[i - 1] != ch]  # dokker, never a triple
    out += [w[:i] + w[i + 1:] for i in range(len(w) - 1) if w[i] == w[i + 1]]   # undouble
    return out


def op_drop_last(w: str) -> list[str]:
    return [w[:-1]] if len(w) >= 5 else []


def op_add_suffix(w: str) -> list[str]:
    """A stray trailing consonant ("lan" -> "land"). Only for short words that end in a
    consonant: elsewhere it reads as noise ("routerd"). No plural -s: that is correct English,
    not a mis-transcription."""
    if len(w) <= 4 and w[-1] not in VOWELS:
        return [w + s for s in ("d", "t") if not w.endswith(s)]
    return []


def op_respell(w: str) -> list[str]:
    return [w[:m.start()] + new + w[m.end():] for old, new in RESPELL_RULES for m in re.finditer(old, w)]


WORD_OPERATORS: dict[str, Callable[[str], list[str]]] = {
    "vowel_swap": op_vowel_swap, "consonant_swap": op_consonant_swap, "double_consonant": op_double_consonant,
    "drop_last": op_drop_last, "add_suffix": op_add_suffix, "respell": op_respell,
}


# phrase-level operators: a word list -> variant texts

def op_split_word(words: list[str]) -> list[str]:
    out = []
    for i, w in enumerate(words):
        if w.isalpha() and len(w) >= 7:
            mid = len(w) // 2
            for cut in sorted({mid, mid - 1, mid + 1}):
                if cut >= 3 and len(w) - cut >= 3:
                    out.append(" ".join(words[:i] + [w[:cut], w[cut:]] + words[i + 1:]))
    return out


def op_merge_words(words: list[str]) -> list[str]:
    return [" ".join(words[:i] + [words[i] + words[i + 1]] + words[i + 2:]) for i in range(len(words) - 1)]


def op_swap_words(words: list[str]) -> list[str]:
    return [" ".join(words[:i] + [words[i + 1], words[i]] + words[i + 2:])
            for i in range(len(words) - 1) if words[i] != words[i + 1]]


def op_drop_filler(words: list[str]) -> list[str]:
    return [" ".join(words[:i] + words[i + 1:]) for i, w in enumerate(words) if w in FILLER_WORDS and len(words) >= 3]


PHRASE_OPERATORS: dict[str, Callable[[list[str]], list[str]]] = {
    "split_word": op_split_word, "merge_words": op_merge_words,
    "swap_words": op_swap_words, "drop_filler": op_drop_filler,
}


def spell_letters(letters: str, term: str = "", alt: bool = False) -> str:
    """Spoken letter names for `letters`. alt=True uses a NON-canonical variant for every letter
    (index chosen by CRC32, not RNG), so it always differs from the canonical spelling."""
    parts = []
    for i, ch in enumerate(letters.upper()):
        options = LETTER_VARIANTS.get(ch)
        if not options:
            return ""
        parts.append(options[1 + zlib.crc32(f"{term}|{i}|{ch}".encode()) % (len(options) - 1)] if alt else options[0])
    return " ".join(parts)


def spoken_digits(term: str, spelled: bool) -> str:
    """Digits and dots spoken aloud ("X.509" -> "x dot five oh nine"); letters stay as written
    or, with spelled=True, become letter names ("eye pea vee four")."""
    out = []
    for chunk in re.findall(r"\d+|\.|[A-Za-z]+", term):
        if chunk.isdigit():
            out += [DIGIT_WORDS[d] for d in chunk]
        elif chunk == ".":
            out.append("dot")
        else:
            out.append(spell_letters(chunk) if spelled else chunk.lower())
    return " ".join(out)


def _synthetic_candidates(term: str) -> list[tuple[str, str]]:
    words = split_words(term)
    lower = [w.lower() for w in words]
    out: list[tuple[str, str]] = []
    for op, fn in WORD_OPERATORS.items():
        for i, w in enumerate(lower):
            if _eligible_site(words[i]):
                out += [(op, " ".join(lower[:i] + [v] + lower[i + 1:])) for v in fn(w) if len(v) >= 3]
    for op, fn in PHRASE_OPERATORS.items():
        out += [(op, v) for v in fn(lower)]
    if any(c.isdigit() for c in term):
        out.append(("spoken_digits", spoken_digits(term, spelled=False)))
        out.append(("spoken_digits_spelled", spoken_digits(term, spelled=True)))
    return out


def generate_variants(term: str, all_terms: list[str] | None = None) -> list[Variant]:
    """Every variant for one term, deterministic. Variants identical to the canonical text or to
    any OTHER dictionary term are dropped (recovering them to this term would be wrong)."""
    all_terms = all_terms if all_terms is not None else [t["term"] for t in get_terms()]
    taken = {t.casefold() for t in all_terms}
    seen = {" ".join(split_words(term)).casefold()}

    def fresh(text: str) -> bool:
        norm = " ".join(split_words(text)).casefold()
        if not text.strip() or norm in seen or text.casefold() in taken or norm in taken:
            return False
        seen.add(norm)
        return True

    variants = [Variant(term, CANONICAL, "canonical", term)]
    for spoken, target in ACRONYM_PHONETIC_MAP.items():
        if target == term and fresh(spoken):
            variants.append(Variant(term, ACRONYM_MAP, "acronym_map", spoken))
    for spoken, target in PHRASE_ALIASES.items():
        if target == term and fresh(spoken):
            variants.append(Variant(term, PHRASE_ALIAS, "phrase_alias", spoken))

    if term.isalpha() and (term.isupper() or term in ("NVMe", "SQLi")):  # a letters-only acronym
        for alt in (False, True):
            spelled = spell_letters(term, term, alt)
            if spelled and fresh(spelled):
                variants.append(Variant(term, SPELLED, "spelled_alt" if alt else "spelled", spelled))
    words = split_words(term)
    if len(words) > 1:
        for i, w in enumerate(words):
            if w.isalpha() and w.isupper() and 2 <= len(w) <= 5:
                lower = [x.lower() for x in words]
                text = " ".join(lower[:i] + [spell_letters(w)] + lower[i + 1:])
                if fresh(text):
                    variants.append(Variant(term, SPELLED_TOKEN, "spell_token", text))
                break

    by_op: dict[str, list[str]] = defaultdict(list)
    for op, text in _synthetic_candidates(term):
        by_op[op].append(text)
    queues = {op: sorted(set(texts), key=lambda t: _key(term, op, t)) for op, texts in by_op.items()}
    order = [*WORD_OPERATORS, *PHRASE_OPERATORS, "spoken_digits", "spoken_digits_spelled"]
    kept = 0
    while kept < SYNTHETIC_CAP and any(queues.get(op) for op in order):
        for op in order:
            while queues.get(op):
                text = queues[op].pop(0)
                if fresh(text):
                    variants.append(Variant(term, SYNTHETIC, op, text))
                    kept += 1
                    break
            if kept >= SYNTHETIC_CAP:
                break
    return variants


# --- evaluation ---------------------------------------------------------------------------------------------

@dataclass
class Result:
    term: str
    category: str
    shape: str
    n_words: int
    family: str
    operator: str
    variant: str
    output: str
    outcome: str  # recovered | missed | garbled | wrong (word-level, case/punctuation-insensitive)
    edits: str    # Mozhi's changes, "original -> replacement", ";"-separated
    exact: bool = False  # output is BYTE-identical to the canonical carrier (hyphens and case too)


def term_shape(entry: dict) -> str:
    t = entry["term"]
    if entry.get("is_acronym"):
        return "acronym_digits" if re.search(r"[\d.]", t) else "acronym"
    if len(split_words(t)) > 1:
        return "phrase"
    return "single_word"


def norm_words(text: str) -> list[str]:
    """Lowercased words as the pipeline's tokenizer sees them (hyphens and dots split words)."""
    return [normalize(t.text) for t in tokenize(text)]


def _contains(words: list[str], sub: list[str]) -> bool:
    return bool(sub) and any(words[i:i + len(sub)] == sub for i in range(len(words) - len(sub) + 1))


def classify(expected: str, sent: str, output: str, term: str) -> str:
    """Word-level and case/punctuation-insensitive, like scripts/evaluate_accuracy.py."""
    out = norm_words(output)
    if out == norm_words(expected):
        return "recovered"
    if out == norm_words(sent):
        return "missed"
    if _contains(out, norm_words(term)):
        return "garbled"
    return "wrong"


def _correct_one(sent: str) -> tuple[str, list[tuple[str, str]]]:
    r = correct_text(sent)
    return r.corrected_text, [(sent[m.start:m.end], m.replacement) for m in r.matches]


def evaluate(
    variants: list[Variant],
    entries: dict[str, dict],
    carrier: str = CARRIER,
    corrector: Callable | None = None,
    workers: int = 1,
) -> list[Result]:
    """Run every variant through the pipeline. `corrector(sentence)` -> (output, [(original,
    replacement)]) defaults to the real pipeline; tests inject fakes."""
    fn = corrector or _correct_one
    sents = [carrier.format(v.text) for v in variants]
    if workers > 1 and corrector is None:
        with ProcessPoolExecutor(max_workers=workers) as pool:
            outputs = list(pool.map(fn, sents, chunksize=16))
    else:
        outputs = [fn(s) for s in sents]
    results = []
    for v, sent, (output, matches) in zip(variants, sents, outputs):
        entry = entries[v.term]
        edits = "; ".join(f"{o} -> {r}" for o, r in matches if o != r)
        expected = carrier.format(v.term)
        results.append(Result(
            v.term, entry["category"], term_shape(entry), len(split_words(v.term)), v.family, v.operator,
            v.text, output, classify(expected, sent, output, v.term), edits, output == expected))
    return results


# --- aggregation -----------------------------------------------------------------------------------------------

@dataclass
class TermRow:
    term: str
    category: str
    shape: str
    n_words: int
    canonical_ok: bool
    evaluated_n: int    # variants excluding the tautological families
    evaluated_caught: int
    synthetic_n: int
    synthetic_caught: int
    failing_operators: str

    @property
    def evaluated_rate(self) -> float | None:
        return self.evaluated_caught / self.evaluated_n if self.evaluated_n else None

    @property
    def synthetic_rate(self) -> float | None:
        return self.synthetic_caught / self.synthetic_n if self.synthetic_n else None


def term_rows(results: list[Result]) -> list[TermRow]:
    by_term: dict[str, list[Result]] = defaultdict(list)
    for r in results:
        by_term[r.term].append(r)
    rows = []
    for term, rs in by_term.items():
        ev = [r for r in rs if r.family not in TAUTOLOGICAL]
        syn = [r for r in rs if r.family == SYNTHETIC]
        control = [r for r in rs if r.family == CANONICAL]
        never = sorted({op for op in {r.operator for r in ev}
                        if not any(r.operator == op and r.outcome == "recovered" for r in ev)})
        rows.append(TermRow(
            term, rs[0].category, rs[0].shape, rs[0].n_words,
            bool(control) and control[0].outcome == "recovered",
            len(ev), sum(r.outcome == "recovered" for r in ev),
            len(syn), sum(r.outcome == "recovered" for r in syn), ", ".join(never)))
    return rows


def _rate(caught: int, n: int) -> str:
    return "n/a" if n == 0 else f"{caught / n * 100:5.1f}%"


def _table(results: list[Result], keyfn, title: str, min_n: int = 1) -> list[str]:
    groups: dict[str, list[Result]] = defaultdict(list)
    for r in results:
        groups[keyfn(r)].append(r)
    lines = [title, f"  {'':<26} {'variants':>8} {'recovered':>9} {'rate':>7}   missed garbled wrong"]
    for key, rs in sorted(groups.items(), key=lambda kv: (sum(x.outcome == "recovered" for x in kv[1]) / len(kv[1]), kv[0])):
        if len(rs) < min_n:
            continue
        c = Counter(r.outcome for r in rs)
        lines.append(f"  {key:<26} {len(rs):>8} {c['recovered']:>9} {_rate(c['recovered'], len(rs)):>7}   "
                     f"{c['missed']:>6} {c['garbled']:>7} {c['wrong']:>5}")
    return lines


def summarize(results: list[Result], n_terms: int, carrier: str, elapsed_s: float) -> str:
    rows = term_rows(results)
    evaluated = [r for r in results if r.family not in TAUTOLOGICAL]
    synthetic = [r for r in results if r.family == SYNTHETIC]
    rec = lambda rs: sum(r.outcome == "recovered" for r in rs)  # noqa: E731
    syn_rates = [t.synthetic_rate for t in rows if t.synthetic_rate is not None]
    ev_rates = [t.evaluated_rate for t in rows if t.evaluated_rate is not None]
    unstable = [t for t in rows if not t.canonical_ok]

    L = [
        "Mozhi full-dictionary coverage (SYNTHETIC corruptions, not real STT errors)",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}   ({elapsed_s:.0f}s)",
        f"Terms: {n_terms}   Variants: {len(results)}   Carrier: {carrier!r}   Fuzzy threshold: {DEFAULT_THRESHOLD}",
        "Recovered = corrected sentence equals the carrier with the canonical term, word by word, ignoring case and",
        "punctuation (so 'two factor authentication' recovers 'two-factor authentication'). Byte-exact is reported too.",
        "",
        "READ THIS FIRST",
        "  - The variants are rule-generated. This measures robustness to what the rules imitate, not real-world",
        "    accuracy. Real accuracy needs real recordings (reports/accuracy_evaluation_summary.txt, 2 files so far).",
        "  - Families canonical / acronym_map / phrase_alias are ~100% by construction and are EXCLUDED from the",
        "    'evaluated' and 'synthetic' numbers below. The informative number is the synthetic family.",
        "",
        "HEADLINE",
        f"  synthetic corruptions, micro:  {rec(synthetic)}/{len(synthetic)} = {_rate(rec(synthetic), len(synthetic)).strip()}",
        f"  synthetic corruptions, macro (mean of per-term rates over {len(syn_rates)} terms): "
        f"{statistics.mean(syn_rates) * 100:.1f}%   median {statistics.median(syn_rates) * 100:.1f}%" if syn_rates else "  no synthetic variants",
        f"  all evaluated variants (synthetic + spelled), micro: {rec(evaluated)}/{len(evaluated)} = {_rate(rec(evaluated), len(evaluated)).strip()}"
        f"   macro {statistics.mean(ev_rates) * 100:.1f}%" if ev_rates else "",
        f"  terms recovered in ALL their synthetic variants: {sum(1 for r in syn_rates if r == 1.0)}   "
        f"in NONE: {sum(1 for r in syn_rates if r == 0.0)}   partially: {sum(1 for r in syn_rates if 0 < r < 1)}",
        f"  byte-exact (hyphens and case too) among recovered synthetic: {sum(r.exact for r in synthetic if r.outcome == 'recovered')}"
        f"/{rec(synthetic)}; the rest are the right words with cosmetic differences",
        "",
    ]
    L += _table(results, lambda r: r.family, "BY FAMILY")
    L += [""] + _table(synthetic, lambda r: r.operator, "BY SYNTHETIC OPERATOR (what kind of corruption is hard)")
    L += [""] + _table(evaluated, lambda r: r.category, "BY CATEGORY (evaluated variants)")
    L += [""] + _table(evaluated, lambda r: r.shape, "BY SHAPE (evaluated variants)")
    L += [""] + _table(synthetic, lambda r: f"{min(r.n_words, 4)}{'+' if r.n_words >= 4 else ''} word(s)", "BY TERM LENGTH (synthetic variants)")

    L += ["", f"CANONICAL FORM ALTERED BY MOZHI ({len(unstable)} terms): correctly-spoken terms that do not survive. A pipeline defect, not a coverage gap."]
    canon = {r.term: r for r in results if r.family == CANONICAL}
    for t in sorted(unstable, key=lambda t: t.term):
        c = canon[t.term]
        L.append(f"  {t.term!r:40} -> {c.output.replace('please check the ', '').replace(' now', '')!r:44} [{c.outcome}] edits: {c.edits or '-'}")

    scored = sorted((t for t in rows if t.synthetic_rate is not None), key=lambda t: (t.synthetic_rate, t.term))
    zero = [t for t in scored if t.synthetic_rate == 0]
    low = [t for t in scored if 0 < t.synthetic_rate < 0.5]
    L += ["", f"NEVER RECOVERED in any synthetic variant ({len(zero)} terms)  [term (n variants, category)]"]
    L += [f"  {t.term} ({t.synthetic_n}, {t.category})" for t in zero]
    L += ["", f"BELOW 50% ({len(low)} terms)  [term: caught/n; operators that never worked]"]
    L += [f"  {t.term}: {t.synthetic_caught}/{t.synthetic_n}; {t.failing_operators}" for t in low]

    spelled_terms = {r.term for r in results if r.family == SPELLED}
    spelled_fail = sorted({t for t in spelled_terms
                           if not any(r.term == t and r.family == SPELLED and r.outcome == "recovered" for r in results)})
    L += ["", f"ACRONYMS WHOSE LETTER-BY-LETTER SPELLING IS NOT RECOVERED ({len(spelled_fail)} of {len(spelled_terms)}): {', '.join(spelled_fail) or 'none'}"]
    no_route = sorted(t.term for t in rows if t.shape == "acronym_digits")
    L += [f"ACRONYMS WITH DIGITS/DOTS (composer is letters-only by design; recovery depends on fuzzy): {', '.join(no_route) or 'none'}"]
    no_variants = sorted(t.term for t in rows if t.evaluated_n == 0)
    L += [f"TERMS WITH NO APPLICABLE EVALUATED VARIANT (untested beyond the control): {', '.join(no_variants) or 'none'}"]

    L += [""] + hyphen_report(results)
    L += ["", "MOST FREQUENT BAD REPLACEMENTS (original -> replacement, wrong/garbled outcomes incl. the canonical control)."]
    L += ["  Lines with one word and one term are candidates for NEVER_MATCH_PAIRS; a word matched to a LONGER term that",
          "  contains it ('injection' -> 'SQL injection') is the DP fragmentation defect."]
    bad = top_replacements(results)
    L += [f"  {n:>3}x  {o!r} -> {rep!r}   ({t} term{'s' if t != 1 else ''})" for (o, rep), n, t in bad] or ["  none"]
    return "\n".join(L) + "\n"


def top_replacements(results: list[Result], limit: int = 14) -> list[tuple[tuple[str, str], int, int]]:
    """Most frequent (original, replacement) edits in wrong/garbled outcomes where the replacement is
    not the intended term: [((original, replacement), count, distinct intended terms)]."""
    counts: Counter = Counter()
    terms: dict[tuple[str, str], set[str]] = defaultdict(set)
    for r in results:
        if r.outcome not in ("wrong", "garbled") or r.family == ACRONYM_MAP:
            continue
        for edit in r.edits.split("; "):
            if " -> " in edit:
                original, repl = edit.split(" -> ", 1)
                if repl != r.term:
                    key = (original.strip().lower(), repl)
                    counts[key] += 1
                    terms[key].add(r.term)
    return [(k, n, len(terms[k])) for k, n in counts.most_common(limit)]


def hyphen_report(results: list[Result]) -> list[str]:
    """Do hyphenated phrase terms recover worse than plain ones, and would hyphen-normalizing the term
    string fix it? The second half is a SCORING-ONLY estimate over the missed variants: the pipeline is
    not re-run, so false positives from such a change are not measured."""
    from app.scorer import combined_score  # local: only this report needs the scorer

    phrase = [r for r in results if r.family == SYNTHETIC and r.shape == "phrase"]
    hy = [r for r in phrase if "-" in r.term]
    plain = [r for r in phrase if "-" not in r.term]
    lines = ["HYPHENATED vs PLAIN PHRASE TERMS (synthetic variants)"]
    if not hy or not plain:
        return lines + ["  not enough data"]
    def fmt(rs):  # noqa: E306
        return f"{sum(r.outcome == 'recovered' for r in rs)}/{len(rs)} = {_rate(sum(r.outcome == 'recovered' for r in rs), len(rs)).strip()}"
    lines.append(f"  hyphenated ({len({r.term for r in hy})} terms): {fmt(hy)}    plain ({len({r.term for r in plain})} terms): {fmt(plain)}")
    for n in sorted({r.n_words for r in hy}):
        a, b = [r for r in hy if r.n_words == n], [r for r in plain if r.n_words == n]
        if a and b:
            lines.append(f"  {n} words: hyphenated {fmt(a)}    plain {fmt(b)}")
    missed = [r for r in hy if r.outcome == "missed"]
    if missed:
        cur = [combined_score(r.variant, r.term)["total"] for r in missed]
        norm = [combined_score(r.variant, r.term.replace("-", " "))["total"] for r in missed]
        clear = sum(c < DEFAULT_THRESHOLD <= n for c, n in zip(cur, norm))
        lines.append(f"  missed hyphenated variants: {len(missed)}; mean score {statistics.mean(cur):.3f} against the hyphenated term "
                     f"vs {statistics.mean(norm):.3f} against the hyphen-normalized term")
        lines.append(f"  would newly clear the {DEFAULT_THRESHOLD} threshold with a hyphen-normalized term: {clear} of {len(missed)} "
                     "(scoring only; false-positive impact not measured)")
    return lines


# --- CSV ---------------------------------------------------------------------------------------------------------------

VARIANT_FIELDS = ["term", "category", "shape", "n_words", "family", "operator", "variant", "outcome", "exact", "output", "mozhi_edits"]
TERM_FIELDS = ["term", "category", "shape", "n_words", "canonical_ok", "evaluated_n", "evaluated_caught", "evaluated_rate",
               "synthetic_n", "synthetic_caught", "synthetic_rate", "failing_operators"]


def write_csvs(results: list[Result], variants_path: Path, terms_path: Path) -> None:
    variants_path.parent.mkdir(parents=True, exist_ok=True)
    with open(variants_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(VARIANT_FIELDS)
        for r in results:
            w.writerow([r.term, r.category, r.shape, r.n_words, r.family, r.operator, r.variant, r.outcome,
                        "yes" if r.exact else "no", r.output, r.edits])
    fmt = lambda x: "" if x is None else f"{x:.3f}"  # noqa: E731
    with open(terms_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(TERM_FIELDS)
        for t in sorted(term_rows(results), key=lambda t: (t.synthetic_rate if t.synthetic_rate is not None else 2, t.term)):
            w.writerow([t.term, t.category, t.shape, t.n_words, "yes" if t.canonical_ok else "NO", t.evaluated_n,
                        t.evaluated_caught, fmt(t.evaluated_rate), t.synthetic_n, t.synthetic_caught,
                        fmt(t.synthetic_rate), t.failing_operators])


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--workers", type=int, default=min(8, os.cpu_count() or 1))
    p.add_argument("--limit", type=int, default=0, help="only the first N terms (quick check)")
    p.add_argument("--terms", default="", help="comma-separated terms to test")
    p.add_argument("--carrier", default=CARRIER)
    p.add_argument("--out-dir", type=Path, default=REPORTS, help="where the three report files go (default: reports/)")
    args = p.parse_args(argv)

    entries = {t["term"]: t for t in get_terms()}
    all_terms = list(entries)
    chosen = [t.strip() for t in args.terms.split(",") if t.strip()] or all_terms
    unknown = [t for t in chosen if t not in entries]
    if unknown:
        print(f"ERROR: not in the dictionary: {unknown}")
        return 1
    if args.limit:
        chosen = chosen[: args.limit]
    variants = [v for t in chosen for v in generate_variants(t, all_terms)]
    print(f"{len(chosen)} terms -> {len(variants)} variants, {args.workers} worker(s)...")
    start = time.time()
    results = evaluate(variants, entries, args.carrier, workers=args.workers)
    summary = summarize(results, len(chosen), args.carrier, time.time() - start)
    out = args.out_dir
    write_csvs(results, out / VARIANTS_CSV.name, out / TERMS_CSV.name)
    (out / SUMMARY_TXT.name).write_text(summary, encoding="utf-8")
    print(summary)
    print(f"Wrote {VARIANTS_CSV.name}, {TERMS_CSV.name}, {SUMMARY_TXT.name} in {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
